### PR TITLE
fix: create conda history file manually

### LINKED ISSUE #7: Add integration tests

### LINKED ISSUE #9: missing `conda-meta/history` file makes conda reject the installed prefix
conda rejects the installed prefix with the following error message:

```text
DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: /opt/conda/envs/jupyter
```

This is because the `conda-meta/history` file is not created by our tool: https://github.com/conda/conda/blob/acf656e8d3c6afd55de3bb489589fb9042926fc8/conda/cli/common.py#L276-L278

@pavelzw should we create the file manually (I think it can be empty?) or is there something built into rattler we can enable?

### PR DESCRIPTION
**Pull request by ytausch**
Hotfix for #9. Also adds the necessary testing.

Closes #9. Closes #7.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1210327008468355

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -120,10 +122,19 @@ async fn main() -> Result<()> {
         .install(&cli.prefix, packages)
         .await?;
 
+    // hotfix: create history file, otherwise the prefix is rejected by conda
+    // can be removed with rattler-conda-types v0.33.0
```
Comment (pavelzw) [inline src/main.rs:126]:
```suggestion
    // TODO: can be removed with rattler-conda-types v0.33.0
```

File: tests/integration_test.rs [hunk 2]
```diff
@@ -1 +1,62 @@
...
+}
+
+#[rstest]
+fn test_install(tmpdir: TempDir) {
+    let test_dir = Path::new("tests/test-env");
+    let target = tmpdir;
+
+    Command::cargo_bin("pixi-install-to-prefix")
+        .unwrap()
+        .current_dir(test_dir)
```
[the remark this answers is not in the document]
Comment (ytausch) [reply tests/integration_test.rs:48]: this is incorrect, pixi-install-to-prefix uses the lockfile from the working dir by default

File: Cargo.toml
Comment (pavelzw) [inline Cargo.toml:1]: let's bump the version here as well

File: tests/integration_test.rs [hunk 3]
```diff
@@ -1 +1,58 @@
...
+    let conda_stdout = str::from_utf8(&conda_output.stdout).unwrap();
+    assert!(conda_stdout.trim_end().ends_with("/bin/python"));
+}
+
+#[rstest]
+fn test_install(tmpdir: TempDir) {
+    let test_dir = Path::new("tests/test-env");
+    let target = tmpdir;
+
+    Command::cargo_bin("pixi-install-to-prefix")
```
Comment (pavelzw) [inline tests/integration_test.rs:46]: i prefer to not use cargo_bin but the proper entrypoint as it makes debugging harder.
(for a single test, it makes sense to use cargo_bin as well, just to see that the whole clap integration works, but for general testing, running the functions directly is better as you see nicer error messages etc)

**Review by pavelzw — APPROVED** [review]

File: tests/integration_test.rs (hunk 3 above)
Comment (ytausch) [reply tests/integration_test.rs:46]: yeah this was meant to be this one single test^^
Currently, we have everything in main, and we can't directly call that here, can we?

Comment (ytausch) [reply tests/integration_test.rs:46]: We can also keep #7 open if you think there is still some work needed (there are also other CLI flags, for example).
